vente_en_ligne/Controllers/AdminsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using vente_en_ligne.Data;
using vente_en_ligne.Models;

namespace vente_en_ligne.Controllers
{
    public class AdminsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AdminsController(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> AdminDashboard()
        {
            return View();
        }
        // GET: Admins
        public async Task<IActionResult> Index()
        {
              return _context.Admin != null ? 
                          View(await _context.Admin.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Admins'  is null.");
        }

        // GET: Admins/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.Admin == null)
            {
                return NotFound();
            }

            var admin = await _context.Admin
                .FirstOrDefaultAsync(m => m.CIN == id);
            if (admin == null)
            {
                return NotFound();
            }

            return View(admin);
        }

        // GET: Admins/Create
        public async Task<IActionResult> Create()
        {
            return PartialView("_Create");
        }
        public async Task<IActionResult> CreateProp()
        {
            return PartialView("_Create");
        }

        // POST: Admins/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CIN,password")] Admin admin)
        {
            if (ModelState.IsValid)
            {
                _context.Add(admin);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(admin);
        }

        // GET: Admins/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _context.Admin == null)
            {
                return NotFound();
            }

            var admin = await _context.Admin.FindAsync(id);
            if (admin == null)
            {
                return NotFound();
            }
            return View(admin);
        }

        // POST: Admins/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("CIN,password")] Admin admin)
        {
            if (id != admin.CIN)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(admin);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AdminExists(admin.CIN))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(admin);
        }

        // GET: Admins/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null || _context.Admin == null)
            {
                return NotFound();
            }

            var admin = await _context.Admin
                .FirstOrDefaultAsync(m => m.CIN == id);
            if (admin == null)
            {
                return NotFound();
            }

            return View(admin);
        }
       

        // POST: Admins/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (_context.Admin == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Admins'  is null.");
            }
            var admin = await _context.Admin.FindAsync(id);
            if (admin != null)
            {
                _context.Admin.Remove(admin);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AdminExists(string id)
        {
          return (_context.Admin?.Any(e => e.CIN == id)).GetValueOrDefault();
        }
    }
}

vente_en_ligne/Controllers/ProprietairesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Humanizer;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using vente_en_ligne.Data;
using vente_en_ligne.Models;

namespace vente_en_ligne.Controllers
{
    public class ProprietairesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ProprietairesController(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> PropriHome()
        {
            return View();
        }
        // GET: Proprietaires
        public async Task<IActionResult> Index(string cin,string password)
        {
            bool authentificationReussie = AuthentificationReussie(cin, password);

            // Si l'authentification réussit, redirigez vers la vue "Create" du contrôleur "Produit"
            if (authentificationReussie)
            {
                // Remplacez "NomDuControleur" par le vrai nom de votre contrôleur "Produit"
                return RedirectToAction("Create", "Produits");
            }
            return _context.Proprietaires != null ? 
                          View(await _context.Proprietaires.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Proprietaires'  is null.");
        }
        private bool AuthentificationReussie(string cin, string password)
        {
            // Votre logique de recherche dans la base de données
            // Assurez-vous que le mot de passe est stocké de manière sécurisée, par exemple en utilisant le hachage

            // Exemple fictif :
            var proprietaire = _context.Proprietaires
                .FirstOrDefault(p => p.INterID == cin && p.password == password);

            // Retournez true si un propriétaire correspondant est trouvé, sinon retournez false
            return proprietaire != null;
        }
        // GET: Proprietaires/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.Proprietaires == null)
            {
                return NotFound();
            }

            var proprietaire = await _context.Proprietaires
                .FirstOrDefaultAsync(m => m.INterID == id);
            if (proprietaire == null)
            {
                return NotFound();
            }

            return View(proprietaire);
        }

        // GET: Proprietaires/Create
        public IActionResult Create()
        {
            return View();
        }
        public async Task<IActionResult> CreateProp()
        {
            return PartialView("_Create");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateProp([Bind("INterID,NomEntreprise,AdresseEntreprise,Nom,Prenom,Tele,Email,password")] Proprietaire proprietaire)
        {
            if (ModelState.IsValid)
            {
                _context.Add(proprietaire);
                await _context.SaveChangesAsync();


                return RedirectToAction(nameof(CreateProp)); // Rediriger vers la même action pour afficher le message
            }

            // Si le modèle n'est pas valide, retourner la vue sans stocker de message
            return View(proprietaire);
        }

        // POST: Proprietaires/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("INterID,NomEntreprise,AdresseEntreprise,Nom,Prenom,Tele,Email,password")] Proprietaire proprietaire)
        {
            if (ModelState.IsValid)
            {
                _context.Add(proprietaire);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(proprietaire);
        }

        // GET: Proprietaires/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _context.Proprietaires == null)
            {
                return NotFound();
            }

            var proprietaire = await _context.Proprietaires.FindAsync(id);
            if (proprietaire == null)
            {
                return NotFound();
            }
            return View(proprietaire);
        }

        // POST: Proprietaires/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("INterID,NomEntreprise,AdresseEntreprise,Nom,Prenom,Tele,Email,password")] Proprietaire proprietaire)
        {
            if (id != proprietaire.INterID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(proprietaire);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProprietaireExists(proprietaire.INterID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(proprietaire);
        }
        public async Task<IActionResult> DeleteProprio()
        {
            return PartialView("_DeleteProprio");
        }
        public async Task<IActionResult> ModifyProprio()
        {
            return PartialView("_ModifyProprio");
        }
        public async Task<IActionResult> ModifyForm()
        {
            return PartialView("_ModifyForm");
        }
        // GET: Proprietaires/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null || _context.Proprietaires == null)
            {
                return NotFound();
            }

            var proprietaire = await _context.Proprietaires
                .FirstOrDefaultAsync(m => m.INterID == id);
            if (proprietaire == null)
            {
                return NotFound();
            }

            return View(proprietaire);
        }

        // POST: Proprietaires/Delete/5
        [HttpPost, ActionName("DeleteConfirmed")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed([Bind("INterID")] Proprietaire proprietaire)
        {
            try
            {
                if (_context.Proprietaires == null)
                {
                    return Problem("Entity set 'ApplicationDbContext.Proprietaires' is null.");
                }

                // Retrieve the proprietaire by ID
                var existingProprietaire = await _context.Proprietaires.FindAsync(proprietaire.INterID);

                if (existingProprietaire == null)
                {
                    return NotFound(); // Return 404 if the proprietaire is not found
                }

                _context.Proprietaires.Remove(existingProprietaire);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(DeleteProprio));
            }
            catch (Exception ex)
            {
                // Log the exception or handle it appropriately
                return Problem($"An error occurred while deleting: {ex.Message}");
            }
        }
        private bool ProprietaireExists(string id)
        {
          return (_context.Proprietaires?.Any(e => e.INterID == id)).GetValueOrDefault();
        }
    }
}

vente_en_ligne/Views/Shared/_Create.cshtml
@model vente_en_ligne.Models.Proprietaire

<script src="~/js/createprop.js"></script>
<link href="~/css/createprop.css" rel="stylesheet" />


<div class='box'>
    <div class='box-form'>
        <div class='box-login-tab'></div>
        <div class='box-login'>
            <form asp-action="CreateProp" method="post" class="sign-in-form">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class='fieldset-body' id='login_form'>
                    <p class='field'>
                        <label for='pass'>CIN/Passeport</label>
                        <input type='text' asp-for="INterID" />
                        <span asp-validation-for="INterID" class="text-danger"></span>
                    </p>
                    <p class='field'>
                        <label for='user'>E-mail</label>
                        <input type='text' asp-for="Email" />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </p>
                    <p class='field'>
                        <label for='pass'>Password</label>
                        <input type='password' asp-for="password" />
                        <span asp-validation-for="password" class="text-danger"></span>
                    </p>
                    <p class='field'>
                        <label for='pass'>Last Name</label>
                        <input type='text' asp-for="Nom" />
                        <span asp-validation-for="Nom" class="text-danger"></span>
                    </p>
                    <p class='field'>
                        <label for='pass'>First Name</label>
                        <input type='text' asp-for="Prenom" />
                        <span asp-validation-for="Prenom" class="text-danger"></span>
                    </p>
                    <p class='field'>
                        <label for='pass'>Phone</label>
                        <input type='text' asp-for="Tele" />
                        <span asp-validation-for="Tele" class="text-danger"></span>
                    </p>
                    <p class='field'>
                        <label for='pass'>Company name</label>
                        <input type='text' asp-for="NomEntreprise" />
                        <span asp-validation-for="NomEntreprise" class="text-danger"></span>
                    </p>
                    <p class='field'>
                        <label for='pass'>Adress</label>
                        <input type='text' asp-for="AdresseEntreprise" />
                        <span asp-validation-for="AdresseEntreprise" class="text-danger"></span>
                    </p>
                    <input type='submit' id='do_login' value='Create' title='Get Started' />
                </div>
            </form>

        </div>
    </div>

</div>


<div class='icon-credits'>Icons made by <a href="http://www.freepik.com" title="Freepik">Freepik</a>, <a href="http://www.flaticon.com/authors/budi-tanrim" title="Budi Tanrim">Budi Tanrim</a> & <a href="http://www.flaticon.com/authors/nice-and-serious" title="Nice and Serious">Nice and Serious</a> from <a href="http://www.flaticon.com" title="Flaticon">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a></div>
<script>
    // Capture de la soumission du formulaire
    $('form').submit(function (e) {
        e.preventDefault(); // Empêche l'envoi du formulaire par défaut

        var form = this;
        var formData = $(form).serialize(); // Récupère les données du formulaire
        $.ajax({
            type: 'POST',
            url: '@Url.Action("CreateProp")', // Votre URL d'action du contrôleur
            data: formData,
            success: function () {
                // Effacer les champs du formulaire après la soumission réussie
                form.reset();
                // Effacer le message de succès après quelques secondes
                setTimeout(function () {
                    $('.alert-success').fadeOut();
                }, 3000); // Disparition du message de succès après 3 secondes
            },
            error: function () {
                // Gestion des erreurs
            }
        });
    });
</script>

vente_en_ligne/Views/Shared/_CreateCat.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

vente_en_ligne/Views/Shared/_DeleteProprio.cshtml
@model vente_en_ligne.Models.Proprietaire

<link href="~/css/deleteproprio.css" rel="stylesheet" />
<main>
    <div class="blur"></div>
    <div class="container">
        <form asp-action="DeleteConfirmed" method="post" >
            <img src="~/img/effacer.png" class="photo"/> 
            <br>
            <input class="datos" type="text" asp-for= "INterID" placeholder="CIN/Passeport">
            <br>
            <br>
            <input class="boton reset" type="submit" value="Delete">
        </form>
    </div>
</main>

vente_en_ligne/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    @RenderSection("Scripts", required: false)
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <title>Electro</title>

    <!-- Google font -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,700" rel="stylesheet">

    <!-- Bootstrap -->
    <link type="text/css" rel="stylesheet" href="css/bootstrap.min.css" />

    <!-- Slick -->
    <link type="text/css" rel="stylesheet" href="css/slick.css" />
    <link type="text/css" rel="stylesheet" href="css/slick-theme.css" />

    <!-- nouislider -->
    <link type="text/css" rel="stylesheet" href="css/nouislider.min.css" />

    <!-- Font Awesome Icon -->
    <link rel="stylesheet" href="css/font-awesome.min.css">

    <!-- Custom stlylesheet -->
    <link type="text/css" rel="stylesheet" href="css/style.css" />

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <style>
        .dropdown-menu li a:hover {
            color: red !important; 
        }
    </style>
</head>
<body>

    <!-- /TOP HEADER -->
    <!-- MAIN HEADER -->
    <div id="header">

        <!-- container -->
        <div class="container">
            <!-- row -->
            <div class="row">
                <!-- LOGO -->
                <div class="col-md-2">
                    <div class="header-logo">
                        <a href="#" class="logo">
                            <img src="./img/e-commerce.png" alt="">
                        </a>
                    </div>
                </div>
                <!-- /LOGO -->
                <!-- SEARCH BAR -->
                <div class="col-md-5 mb-3 mr-auto" style="margin-left: 60px; margin-right: 100px">
                    <div class="header-search" >
                        <form>
                            <select class="input-select">
                                <option value="0">All Categories</option>
                                <option value="1">Vehicle</option>
                                <option value="1">Multimedia</option>
                            </select>
                            <input class="input" placeholder="Search here">
                            <button class="search-btn">Search</button>
                        </form>
                    </div>
                </div>
                <!-- /SEARCH BAR -->
                <!-- ACCOUNT -->
                <div class="col-md-3 clearfix ml-auto" style="margin-left: 2px">
                    <div class="header-ctn">
                       
                        <!-- Cart -->
                        <div >
                                <a href="#" class="dropdown-toggle"><i class="fa fa-shopping-cart"></i>Your Cart</a>

                        </div>
                        <!-- Icone pour déclencher la liste déroulante -->
                        <div class="dropdown">
                            <a href="#" class="dropdown-toggl"><i class="fa fa-user-o"></i>Log In</a>
                            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <li><a href="@Url.Action("Index", "Proprietaires")">Owner</a></li>
                                <li><a href="@Url.Action("Index", "Admins")">Administrator</a></li>
                            </ul>

                        </div>
                        <div>
                            <a href="#" class="dropdown-toggle"><i class="fa fa-globe"></i>Languages</a>
                          
                            </ul>
                        </div>
                        <!-- /Cart -->
                    </div>
                </div>
                <!-- /ACCOUNT -->
            </div>
            <!-- row -->
        </div>
        <!-- container -->
    </div>
    <!-- /MAIN HEADER -->
    </header>
    @RenderBody()
    <script>
        $(document).ready(function () {
            $(".dropdown-toggl").on("click", function (e) {
                e.preventDefault();
                $(".dropdown-menu").slideToggle();
            });

            $(".dropdown-menu li a").on("click", function (e) {
                e.preventDefault();
                var pageLink = $(this).attr("href");
                window.location.href = pageLink;
            });
        });

    </script>

</body>
</html>

vente_en_ligne/Views/Shared/_ModifyForm.cshtml
<script src="~/js/createprop.js"></script>
<link href="~/css/createprop.css" rel="stylesheet" />
<div class='box'>
    <div class='box-form'>
        <div class='box-login-tab'></div>
        <div class='box-login'>
            <div class='fieldset-body' id='login_form'>
                <p class='field'>
                    <label for='user'>E-mail</label>
                    <input type='text' id='user' name='user' title='Username' />
                    <span id='valida' class='i i-warning'></span>
                </p>
                <p class='field'>
                    <label for='pass'>Password</label>
                    <input type='password' id='pass' name='pass' title='Password' />
                    <span id='valida' class='i i-close'></span>
                </p>
                <p class='field'>
                    <label for='pass'>Last Name</label>
                    <input type='text' id='pass' name='pass' title='Password' />
                    <span id='valida' class='i i-close'></span>
                </p>
                <p class='field'>
                    <label for='pass'>First Name</label>
                    <input type='text' id='pass' name='pass' title='Password' />
                    <span id='valida' class='i i-close'></span>
                </p>
                <p class='field'>
                    <label for='pass'>CIN/Passeport</label>
                    <input type='text' id='pass' name='pass' title='Password' />
                    <span id='valida' class='i i-close'></span>
                </p>
                <p class='field'>
                    <label for='pass'>Phone</label>
                    <input type='text' id='pass' name='pass' title='Password' />
                    <span id='valida' class='i i-close'></span>
                </p>
                <p class='field'>
                    <label for='pass'>Company name</label>
                    <input type='text' id='pass' name='pass' title='Password' />
                    <span id='valida' class='i i-close'></span>
                </p>
                <p class='field'>
                    <label for='pass'>Adress</label>
                    <input type='text' id='pass' name='pass' title='Password' />
                    <span id='valida' class='i i-close'></span>
                </p>
                <input type='submit' id='do_login' value='Create' title='Get Started' />
            </div>
        </div>
    </div>

</div>


<div class='icon-credits'>Icons made by <a href="http://www.freepik.com" title="Freepik">Freepik</a>, <a href="http://www.flaticon.com/authors/budi-tanrim" title="Budi Tanrim">Budi Tanrim</a> & <a href="http://www.flaticon.com/authors/nice-and-serious" title="Nice and Serious">Nice and Serious</a> from <a href="http://www.flaticon.com" title="Flaticon">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a></div>

vente_en_ligne/Views/Shared/_ModifyProprio.cshtml
<link href="~/css/modifyproprio.css" rel="stylesheet" />
<script src="~/js/modifyproprio.js"></script>
<form>
	<input name="name" type="text" class="feedback-input" placeholder="CIN/Passeport" />
	<a href="#" type="submit" value="Search" onclick="loadContent('ModifyForm')" class="search">Search</a>
</form>