vente_en_ligne/Models/Produit.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace vente_en_ligne.Models
{
    public class Produit
    {
        [Key]
        public int IdPr { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public double prix { get; set; }

        [ForeignKey("Categorie")]
        public int IDC { get; set; }
        public Categories Categories { get; set; }

        [ForeignKey("Proprietaire")]
        public string IDP { get; set; }
        public Proprietaire proprietaires { get; set; }
        public DateTime DateDepot { get; set; }
        public byte[] ImageData { get; set; }
        public int stock { get; set; }

    }
}

vente_en_ligne/Controllers/ProduitsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using vente_en_ligne.Data;
using vente_en_ligne.Models;

namespace vente_en_ligne.Controllers
{
    public class ProduitsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ProduitsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Produits
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Produits.Include(p => p.Categories).Include(p => p.proprietaires);
            return View(await applicationDbContext.ToListAsync());
        }
       


        // GET: Produits/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Produits == null)
            {
                return NotFound();
            }

            var produit = await _context.Produits
                .Include(p => p.Categories)
                .Include(p => p.proprietaires)
                .FirstOrDefaultAsync(m => m.IdPr == id);
            if (produit == null)
            {
                return NotFound();
            }

            return View(produit);
        }

        // GET: Produits/Create
        public IActionResult Create()
        {
            ViewData["IDC"] = new SelectList(_context.Categories, "CategorieID", "CategorieID");
            ViewData["IDP"] = new SelectList(_context.Proprietaires, "INterID", "INterID");
            return View();
        }

        // POST: Produits/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdPr,Name,Description,prix,IDC,IDP,DateDepot,ImageData,stock")] Produit produit)
        {
            if (ModelState.IsValid)
            {
                _context.Add(produit);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["IDC"] = new SelectList(_context.Categories, "CategorieID", "CategorieID", produit.IDC);
            ViewData["IDP"] = new SelectList(_context.Proprietaires, "INterID", "INterID", produit.IDP);
            return View(produit);
        }

        // GET: Produits/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Produits == null)
            {
                return NotFound();
            }

            var produit = await _context.Produits.FindAsync(id);
            if (produit == null)
            {
                return NotFound();
            }
            ViewData["IDC"] = new SelectList(_context.Categories, "CategorieID", "CategorieID", produit.IDC);
            ViewData["IDP"] = new SelectList(_context.Proprietaires, "INterID", "INterID", produit.IDP);
            return View(produit);
        }

        // POST: Produits/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdPr,Name,Description,prix,IDC,IDP,DateDepot,ImageData,stock")] Produit produit)
        {
            if (id != produit.IdPr)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(produit);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProduitExists(produit.IdPr))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IDC"] = new SelectList(_context.Categories, "CategorieID", "CategorieID", produit.IDC);
            ViewData["IDP"] = new SelectList(_context.Proprietaires, "INterID", "INterID", produit.IDP);
            return View(produit);
        }

        // GET: Produits/Delete/5

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Produits == null)
            {
                return NotFound();
            }

            var produit = await _context.Produits
                .Include(p => p.Categories)
                .Include(p => p.proprietaires)
                .FirstOrDefaultAsync(m => m.IdPr == id);
            if (produit == null)
            {
                return NotFound();
            }

            return View(produit);
        }

        // POST: Produits/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Produits == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Produits'  is null.");
            }
            var produit = await _context.Produits.FindAsync(id);
            if (produit != null)
            {
                _context.Produits.Remove(produit);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProduitExists(int id)
        {
          return (_context.Produits?.Any(e => e.IdPr == id)).GetValueOrDefault();
        }
    }
}

vente_en_ligne/Views/Produits/Create.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>DarkPan - Bootstrap 5 Admin Template</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="/img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&family=Roboto:wght@500;700&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" rel="stylesheet" />

    <!-- Libraries Stylesheet -->
    <link href="/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
    <link href="/lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css" rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="/css/bootstrap.minP.css" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="/css/styleP.css" rel="stylesheet">
    <link rel="stylesheet" href="/css/stylePr.css" />
    <style>
        .image-container {
            display: inline-block;
            position: relative;
        }

        .image-preview {
            max-width: 100%;
            max-height: 200px; /* Set a maximum height for the image preview */
            border: 1px solid #ddd; /* Add a border for better visibility */
            border-radius: 4px; /* Optional: Add border-radius for a rounded appearance */
            margin-top: 10px;
            height:250px;
            width : 300px;
        }

        .choose-button {
            cursor: pointer;
            color: blue;
            text-decoration: underline;
        }
    </style>

</head>

<body>
    <div class="container-fluid position-relative d-flex p-0" style="background-color: #001f3f">
        <!-- Spinner Start -->
        <div id="spinner" class="show  position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center" style="background-color: #001f3f">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
        <!-- Spinner End -->
        <!-- Sidebar Start -->
        <div class="sidebar pe-4 pb-3" style="background-color: #001f3f; color: white;">
            <nav class="navbar" style="background-color: #001f3f ">
                <img src="~/img/e-commerce.png" class="image" />

                <a href="index.html" class="navbar-brand mx-4 mb-3 d-flex align-items-center" style="background-color: #001f3f;">
                </a>

                <div class="navbar-nav w-100" style="background-color: #001f3f; color: white;">
                    <a href="index.html" class="nav-item nav-link active" style="background-color: #001f3f">
                        <i class="far fa-smile fa-lg me-2" style="background-color: #001f3f"></i> Welcome Owner
                    </a>

                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown" style="background-color: #001f3f">
                            <i class="fas fa-shopping-bag fa-lg me-2" style="background-color: #001f3f;"></i> Products
                        </a>
                        <div class="dropdown-menu border-0" style="background-color: #001f3f; padding: 10px;">
                            <a href="@Url.Action("Create", "Produits")" class="dropdown-item ">Add Product</a>
                            <a href="#" class="dropdown-item ">Delete Product</a>
                            <a href="#" class="dropdown-item ">Update Product</a>
                        </div>
                    </div>

                    <a href="#" class="nav-item nav-link" style="background-color: #001f3f"><i class="fa fa-th me-2" style="background-color: #001f3f"></i>Recent sales</a>
                    <a href="#" class="nav-item nav-link" style="background-color: #001f3f"><i class="fa fa-keyboard me-2" style="background-color: #001f3f"></i>Visit Products</a>
                    <a href="" class="nav-item nav-link" style="background-color: #001f3f"><i class="fa fa-chart-bar me-2" style="background-color: #001f3f"></i>Statistics</a>

                </div>
            </nav>
        </div>
        <!-- Sidebar End -->
        <!-- Content Start -->
        <div class="content" style="background-color: #AED6F1; color: white;">
            <!-- Navbar Start -->
            <nav class="navbar navbar-expand  sticky-top px-4 py-0" style="background-color: #001f3f; color: white;">
                <a href="index.html" class="navbar-brand d-flex d-lg-none me-4" style="background-color: #001f3f;">
                    <h2 class="text-primary mb-0"><i class="fa fa-user-edit" style="background-color: #001f3f;"></i></h2>
                </a>
                <a href="#" class="sidebar-toggler flex-shrink-0" style="background-color: #001f3f;">
                    <i class="fa fa-bars" style="background-color: #001f3f;"></i>
                </a>

                <div class="navbar-nav align-items-center ms-auto" style="background-color: #001f3f;">
                    <div class="nav-item dropdown" style="background-color: #001f3f;">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown" style="background-color: #001f3f;">
                            <img class="rounded-circle me-lg-2" src="/img/profil.png" alt="" style="width: 40px; height: 40px;">
                            <span class="d-none d-lg-inline-flex">Owner</span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-end  border-0 rounded-0 rounded-bottom m-0" style="background-color: #001f3f;">
                            <a href="#" class="dropdown-item">My Profile</a>
                            <a href="#" class="dropdown-item">Log Out</a>
                        </div>
                    </div>
                </div>
            </nav>
            
            <form style="background-color: #001f3f;">
                <div class="corps-formulaire">
                    <div class="gauche">
                        <div class="groupe">
                            <label>Product's Name</label>
                            <input type="text" name="Name" autocomplete="off" />
                            <i class="fas fa-shopping-bag fa-lg me-2" style="color: red;"></i>
                        </div>

                        <div class="groupe">
                            <label>Give the price</label>
                            <input type="text" name="Prix" autocomplete="off" />
                            <i class="fas fa-dollar-sign fa-lg me-2" style="color: red;"></i>
                        </div>

                        <div class="groupe">
                            <label>The date of launch</label>
                            <input type="text" name="DATE_DEPOT" autocomplete="off" />
                            <i class="fas fa-calendar-alt fa-lg me-2" style="color: red;"></i>
                        </div>

                        <div class="groupe">
                            <label>The quantity offered</label>
                            <input type="text" name="Stock" autocomplete="off" />
                            <i class="fas fa-cubes fa-lg me-2" style="color: red;"></i>
                        </div>
                        <div class="groupe">
                            <label><i class="fas fa-info-circle" style="color:red;"></i>Add some Details</label>
                            <input type="text"  style="width: 100%;" />
                        </div>

                        
                    </div>

                    <div class="droite">
                        <div class="groupe">
                            <label for="imageFile">Choose your image:</label>
                            <span class="choose-button" onclick="chooseFile()" style="color:red;">Choose File</span>
                            <input type="file" name="imageFile" id="imageFile" accept=".jpg, .jpeg, .png" style="display: none;"
                                   onchange="handleImageSelect(this)" />
                            <img id="imagePreview" class="image-preview" src="#" alt="Image Preview" style="display: none;" />
                        </div>

                    </div>
                </div>

                <div class="pied-formulaire" align="center" style="margin-top: 20px;">
                    <button style="background-color: red; color: white;">Add the Product</button>
                </div>

            </form>


            <!-- the JavaScript Code -->
            <script>
                function chooseFile() {
                    document.getElementById('imageFile').click();
                }

                function handleImageSelect(input) {
                    const file = input.files[0];

                    if (file) {
                        const imgElement = document.getElementById('imagePreview');

                        // Display the selected image preview
                        imgElement.src = URL.createObjectURL(file);
                        imgElement.style.display = 'block';
                    }
                }
            </script>
            <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
        </div>

        <!-- JavaScript Libraries -->
        <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
        <script src="/lib/chart/chart.min.js"></script>
        <script src="/lib/easing/easing.min.js"></script>
        <script src="/lib/waypoints/waypoints.min.js"></script>
        <script src="/lib/owlcarousel/owl.carousel.min.js"></script>
        <script src="/lib/tempusdominus/js/moment.min.js"></script>
        <script src="/lib/tempusdominus/js/moment-timezone.min.js"></script>
        <script src="/lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js"></script>

        <!-- Template Javascript -->
        <script src="/js/mainP.js"></script>
</body>

</html>

vente_en_ligne/Views/Produits/Delete.cshtml
@model vente_en_ligne.Models.Produit

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Produit</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.prix)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.prix)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Categories)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Categories.CategorieID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.proprietaires)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.proprietaires.INterID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateDepot)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateDepot)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImageData)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImageData)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.stock)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.stock)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="IdPr" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

vente_en_ligne/Views/Produits/Details.cshtml
@model vente_en_ligne.Models.Produit

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Produit</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.prix)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.prix)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Categories)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Categories.CategorieID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.proprietaires)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.proprietaires.INterID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateDepot)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateDepot)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImageData)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImageData)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.stock)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.stock)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.IdPr">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

vente_en_ligne/Views/Produits/Edit.cshtml
@model vente_en_ligne.Models.Produit

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Produit</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdPr" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="prix" class="control-label"></label>
                <input asp-for="prix" class="form-control" />
                <span asp-validation-for="prix" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IDC" class="control-label"></label>
                <select asp-for="IDC" class="form-control" asp-items="ViewBag.IDC"></select>
                <span asp-validation-for="IDC" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IDP" class="control-label"></label>
                <select asp-for="IDP" class="form-control" asp-items="ViewBag.IDP"></select>
                <span asp-validation-for="IDP" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateDepot" class="control-label"></label>
                <input asp-for="DateDepot" class="form-control" />
                <span asp-validation-for="DateDepot" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageData" class="control-label"></label>
                <input asp-for="ImageData" class="form-control" />
                <span asp-validation-for="ImageData" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="stock" class="control-label"></label>
                <input asp-for="stock" class="form-control" />
                <span asp-validation-for="stock" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

vente_en_ligne/Views/Produits/Index.cshtml
@model IEnumerable<vente_en_ligne.Models.Produit>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.prix)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Categories)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.proprietaires)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateDepot)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ImageData)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.stock)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.prix)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Categories.CategorieID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.proprietaires.INterID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateDepot)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ImageData)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.stock)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.IdPr">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.IdPr">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.IdPr">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>